name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install system dependencies
        run: |
          brew update
          brew install libimobiledevice

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libimobiledevice-dev libplist-dev libusbmuxd-dev libssl-dev

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
